#!/usr/bin/env ansible-playbook
# export DB_PASS=RandomPostgresWords
---

- name: Database Server
  hosts: database
  become: true
  gather_facts: true

  roles:
    - role: postgres
      tags: [postgres]

- name: Semaphore
  hosts: semaphore
  become: true
  gather_facts: true
  roles:
    - role: docker
      tags: [docker]
    - role: semaphore
      tags: [semaphore]

- name: Reverse Proxy
  hosts: web
  become: true
  gather_facts: true
  roles:
    - role: nginx
      tags: [nginx]
