---
# https://github.com/roles-ansible/ansible_role_gitea
# Here we assume we are behind a reverse proxy that will
# handle https for us, so we bind on localhost:3000 using HTTP
# see https://docs.gitea.io/en-us/reverse-proxies/#nginx
gitea_fork: forgejo
gitea_force_private: true
gitea_fqdn: "{{ ansible_fqdn | default(ansible_hostname) }}"
gitea_http_port: 3000
gitea_protocol: http
gitea_root_url: "https://{{ ansible_fqdn | default(ansible_hostname) }}"
gitea_shell: /bin/bash
gitea_ssh_port: 2222 # assuming the host SSH server is running on port 22
gitea_ssh_user: git
gitea_start_ssh: false # to not start the built-in SSH server
gitea_systemd_cap_net_bind_service: true
gitea_user: git # otherwise there will be permission issues
