---
docker_users:
  - "{{ ansible_user }}"
docker_install_compose: true
docker_install_compose_plugin: true
server_name: "{{ lookup('env', 'HOSTNAME') }}"
ssh_passphrase: "{{ lookup('env', 'SSH_PASS') }}"
